Use saved exit status correctly
Previously, we'd have exited 0, assuming the echo command succeeded.
Thanks, shellcheck!

Signed-off-by: Simon McVittie <smcv@collabora.com>

diff --git a/pressure-vessel-wrap b/pressure-vessel-wrap
--- a/pressure-vessel-wrap
+++ b/pressure-vessel-wrap
@@ -351,5 +351,5 @@ if [ -n "$verbose" ]; then
 fi
 
 exec "$BWRAP" $bwrap_end_of_options "$@" || e=$?
-echo "$me: failed to execute '$BWRAP $*': exec status $?" >&2
-exit $?
+echo "$me: failed to execute '$BWRAP $*': exec status $e" >&2
+exit "$e"
